--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IcyEndymion004/Slapper-Addons-UPDATED
build-by-default: true
branches:
- main
projects:
  SlapBack-master:
    path: SlapBack-master/
  SlapperCooldown-master:
    path: SlapperCooldown-master/
  SlapperPlus-master:
    path: SlapperPlus-master/
...
